### ISSUE TITLE
These are not LG WebOS2 drivers

### ISSUE THREAD

**Issue by jwr456** [davydotcom/control4-lg-webos2#1]
Both files are drivers for the Sharp LC-60LE925UN.  Either push real drivers or remove these.  You are serving up the wrong drivers and in Google's top 10 search results for "LG WebOS IP Driver Control4"

**Comment by davydotcom** [comment]
They are incomplete and need work but definitely not removing an open source project that people can contribute to. Also that tv is webos 2 and this works on ties into webos2 websocket protocols to make it happen which is universal across these tvs. It's simply paired with that tv as it's the one I have to test with

**Comment by nmoinvaz** [comment]
I was not able to get it working. Tried the default port 10002 and 3000 but no luck.

**Comment by AndresSalazar1** [comment]
Hey, Can you help me with the setup?
